### ISSUE TITLE
CMake configuration fails when using vcpkg to install dependencies

### ISSUE THREAD

**Issue by s13n** [sony/nmos-cpp#110]
I was trying to install dependencies such as cpprestsdk in a more comfortable manner using vcpkg. Note that Microsoft recommends vcpkg with cpprestsdk, see https://github.com/microsoft/cpprestsdk

CMake configuration fails with the following error:
```
Found cpprestsdk
CMake Error at C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:285 (_find_package):
  Could not find a configuration file for package "websocketpp" that is
  compatible with requested version "0.5.1".

  The following configuration files were considered but not accepted:

    C:/src/vcpkg/installed/x64-windows/share/websocketpp/websocketpp-config.cmake, version: unknown

Call Stack (most recent call first):
  cmake/NmosCppCommon.cmake:49 (find_package)
  CMakeLists.txt:11 (include)


Configuring incomplete, errors occurred!
```

A newer version of websocketpp was installed by vcpkg along with cpprestsdk, but somehow it doesn't get accepted.

It would be nice to be able to use vcpkg, as it simplifies things when using external libraries on Windows.

**Comment by garethsb-sony** [comment]
The issue with finding a more recent version of WebSocket++ is probably due to https://github.com/sony/nmos-cpp/blob/master/Development/cmake/NmosCppCommon.cmake#L49. Version 0.5.1 is the minimum acceptable version for nmos-cpp but e.g. 0.8.1 is OK and I don't think `find_package` has a way to quickly express this. Try deleting the version number from this line.

With respect to vcpkg, I'm always happy to look at PRs related to the meta-build, but I'm not very interested in maintaining support for a Windows-only package management system. The existing documented CMake-only approach seems to work reliably for many nmos-cpp users on Windows and Linux.
