### ISSUE TITLE
How to discover the resources on the network.

### ISSUE THREAD

**Issue by JamieLuo** [sony/nmos-cpp#134]

**Comment by garethsb-sony** [comment]
I suggest you look at [Networked Media Open Specifications: Introduction](http://amwa-tv.github.io/nmos/) and then [AMWA IS-04 NMOS Discovery and Registration](https://amwa-tv.github.io/nmos-discovery-registration/) which explains how NMOS uses DNS Service Discovery (DNS-SD).

**Comment by JamieLuo** [comment]
Sorry I did not add the contents when I open this issue, I added it just now.

**Comment by garethsb-sony** [comment]
In peer-to-peer operation, each Node advertises itself, so that a Controller (either standalone or built into a Node) could discover the Nodes in a small ad-hoc network without using a Registry. The **nmos-cpp** project does not include an implementation of a Controller (either type).

The **nmos-js** project is a browser-based Controller app, but it only supports registered operation, not peer-to-peer mode.

**Comment by JamieLuo** [comment]
OK, thank you for your replying. ; )

**Comment by garethsb-sony** [comment]
No problem! Note that peer-to-peer operation is optional from v1.3 of the specification. Registered operation is recommended.
