### ISSUE TITLE
Testing unicast discovery fails when using non-management interface by the node and to configure DNS server IP

### ISSUE THREAD

**Issue by MohammadQurt** [sony/nmos-cpp#168]
Hi,
I'm running nmos-cpp-node on Windows server with Mellanox ConnectX (non-management) interface by defining ConnectX IP as the _"host_address"_ in the node config.json file.

And running AMWA NMOS testing tool on another Linux server using unicast mode to run IS-04-01 tests.

When configuring DNS server IP for the node on Windows management interface, IS-04-01 tests pass. Noting again that ConnectX interface is used as the _"host_address"_ in the node config.json file.

But when configuring DNS server IP on ConnectX interface the node can't find the registry and the tests fail "Node did not attempt to register with the advertised registry".

Noting that Windows/Linux management IPs and ConnectX IPs are on different subnets, and AMWA tool on Linux was updated to use ConnectX IP by updating _TestHelper.py:get_default_ip()_ to return ConnectX IP instead of the management one.

My questions are:
Is there something I'm doing wrong? Is it correct behavior to configure DNS IP on the management interface while testing the ConnectX one?
Does nmos-cpp uses some default configuration which works with management IP? If so, how can I make it use ConnectX IP instead? so we configure DNS server IP on the ConnectX interface.
And Last, AFAYN, is updating _TestHelper.py:get_default_ip()_ to return ConnectX IP is a correct way to make the tool run on? or is there another way to do so?

Sorry for the many questions & Thanks in advance.

**Comment by rhastie** [comment]
Mohammad,

This does not sound related to the nmos-cpp software stack nor the nmos-testing tool. nmos-cpp and the testing tool simply utilise the underlying DNS client of your host OS. To me it appears that you have the DNS configuration wrongly configured on your Windows platform. The fact that it operates correctly on one interface and fails on another leads me to this conclusion.

Specifically for Windows... The DNS Client service queries the DNS servers in the following order:

1. The DNS Client service sends the name query to the first DNS server on the preferred adapter’s list of DNS servers and waits one second for a response.
2. If the DNS Client service does not receive a response from the first DNS server within one second, it sends the name query to the first DNS servers on all adapters that are still under consideration and waits two seconds for a response.
3. If the DNS Client service does not receive a response from any DNS server within two seconds, the DNS Client service sends the query to all DNS servers on all adapters that are still under consideration and waits another two seconds for a response.
4. If the DNS Client service still does not receive a response from any DNS server, it sends the name query to all DNS servers on all adapters that are still under consideration and waits four seconds for a response.
5. If it the DNS Client service does not receive a response from any DNS server, the DNS client sends the query to all DNS servers on all adapters that are still under consideration and waits eight seconds for a response.

**The preferred adapter in step 1 being the adapter that's listed first in the binding order.**

The last point I think is key to your issue here... You don't say what version of Windows you are running - there are different processes to define the binding order in Win 10, Win Server and other Window versions.

**Comment by MohammadQurt** [comment]
Richard contacted offline with me. And its seems to be DNS resolution issue. I'll close this as its not nmos-cpp/nmos-testing SW issue. Thanks.
