### ISSUE TITLE
nmos::details::make_sdp_parameters in sdp_utils in case of audio always reprting ptime 1 and payload id 97

### ISSUE THREAD

**Issue by aholzinger** [sony/nmos-cpp#202]
I'm currently stumpling upon this one (sdp_utils.cpp line 190):
```
params.packet_time = 1;

return{ sender.at(nmos::fields::label).as_string(), params, 97, media_stream_ids, details::make_ts_refclk(node, source, sender, ptp_domain) };
```

Wouldn't it be nice if the function would correctly report packet time and payload id?

The problem seems to be that in the data provided in the function parameters neither ptime nor pid are contained.

**Comment by garethsb** [comment]
Those values are not found in the NMOS resources. If your app knows them, it can set them. Like the example app, https://github.com/sony/nmos-cpp/blob/master/Development/nmos-cpp-node/node_implementation.cpp#L911

**Comment by aholzinger** [comment]
That's how I worked around it.

Wouldn't it then be better to return invalid values for the two parameters so that the user will immediately be aware to update these parameters?

**Comment by garethsb** [comment]
It's a little awkward because the format-specific functions in `nmos::details` are exposed to the user only via:

https://github.com/sony/nmos-cpp/blob/4fba3ab6db1b0361d625fc3d7edf307145f5a653/Development/nmos/sdp_utils.h#L23

Adding an `optional<uint64_t> payload_type = nullopt` to that function declaration would be OK, I guess.

But it feels a little wrong to add the (basically) audio-specific `double packet_time` to this function's parameter list.

So I'm not sure of the best approach...

> pre-fetched correct values from the SDP

For what it's worth, depending on the structure of your app, the `get_session_description_sdp_parameters` function and therefore also `parse_session_description` can do this for you.
