### ISSUE TITLE
Broken Linux build: `kDNSServiceErr_Timeout` constant is not defined in Avahi compatibility layer

### ISSUE THREAD

**Issue by TSPMP** [sony/nmos-cpp#3]
See https://github.com/lathiat/avahi/blob/master/avahi-compat-libdns_sd/dns_sd.h

The `kDNSServiceErr_*` constants are only defined up to `kDNSServiceErr_BadTime = -65559` in the Avahi compatibility layer in contrast to Bonjour defining them up to `kDNSServiceErr_Timeout = -65568` (see https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwi76IKRwNXZAhUIzKQKHVbEDP0QFggpMAA&url=https%3A%2F%2Fopensource.apple.com%2Fsource%2FmDNSResponder%2FmDNSResponder-541%2FmDNSShared%2Fdns_sd.h&usg=AOvVaw2RjB-6h92rQbWc6xACuFJq).

**Comment by garethsb-sony** [comment]
Thank you for the report!

DNS-SD interoperability (e.g. on machines running both Avahi and Bonjour/mdnsd) and cross-platform portability has turned out to be much harder than it should be. I'll consider how to fix this specific issue, possibly using an older (pre-Leopard) error. I haven't actually built this code against Avahi yet, so I haven't tested whether its compatibility layer is compatible enough.
