### ISSUE TITLE
Is it impossible to register resources simultaneously?

### ISSUE THREAD

**Issue by naeoc4509** [sony/nmos-cpp#359]
I registered 'one receiver' on both sides of two different machines with nmos-cpp installed,
I want to check the registry status on each machine.
But when I tested it,
The receiver is registered only on one of the two machines, and cannot be registered at the same time.
Is it impossible to register resources simultaneously?
If possible, how should I set it up?

**Comment by jonathan-r-thorpe** [comment]
Yes, it is possible to register many resources simultaneously.

This sort of problem often happens if there is more than one registry running on your network.  It is also worth checking that each node is configured to correctly to discover your registry.

If this isn't the problem then please provide details of the platform you are running on as well as the logs of the nodes and registry.

**Comment by jonathan-r-thorpe** [comment]
It is possible to have more than one registry on the network - each registry has a [priority](https://specs.amwa.tv/is-04/releases/v1.1.0/docs/3.1._Discovery_-_Registered_Operation.html) which can be configured in the registry config.json.

However, for development purposes it is simpler to have a single registry for your whole network. I suggest disabling all but one registry and see if that resolves matters.

**Comment by garethsb** [comment]
This is a feature of the NMOS spec, a Node is only registered with one Registration API at a time. This is described in [IS-04 Registered Operation](https://specs.amwa.tv/is-04/releases/v1.3.2/docs/Discovery_-_Registered_Operation.html#client-interaction-procedure).

Two (or more) Registry instances MAY share a common backend, so that Nodes using either of their Registration APIs makes those resources visible in the Query API of both instances. But nmos-cpp does not support this out-of-the-box.

**Comment by naeoc4509** [comment]
Thank you all so much for your replies.

And I have more questions,
Can I ask a question about 'rhastie/nmos-cpp' docker here?

I am testing on 3 machines as per the question to use nmos.
A is sending a video stream, so it is only implemented. (has no registration, has only node and conneciton api)
B became a node implementatoin by installing 'rhastie/nmos-cpp' docker, and I created a Receiver there to receive A's video stream.

But the problem is C
I Installed 'rhastie/nmos-cpp' docker in C to create a Receiver,
I want to receive another video stream from A.
After installing docker, the registry started automatically, and nodes A and B were not found in C's registry.
(C were not found in B's registry also...)

Nodes A and B is found in B's registry, so streaming is working well.

In this state, if I stop B's docker, only then A's node be found in C's registry.

So my questions are two.
1.
When running 'rhastie/nmos-cpp' docker, is there a way to only do implemetaion and not run a registry on my own machine?
2.
Or, is there a way to ensure that all nodes are registered equally in the registry held by all machines in the network?

Sorry to ask too much T.T,
I have to add more machines for nmos receivers on same network, this is the starting of my test. I need your help

**Comment by naeoc4509** [comment]
Thank you so much! so helpful!
