### ISSUE TITLE
mDNSResponder doesn't support unicast DNS-SD on Linux

### ISSUE THREAD

**Issue by billt-hlit** [sony/nmos-cpp#41]
I'm trying to get unicast DNS-SD set up (thanks for the examples on the wiki, Gareth) and have run into an ugly tight loop in nmos-cpp-node. If I run the command

    nmos-cpp-node '{"logging_level":-2,  "domain": "undefined.local"}'

I get hammered with error messages like

> 2019-01-02 20:55:04.162: warning: 140737013049088: Did not discover a suitable Registration API via DNS-SD
> 2019-01-02 20:55:04.162: info: 140737013049088: Attempting discovery of a Registration API
> 2019-01-02 20:55:04.162: error: 140737080190720: DNSServiceBrowse reported error: -65540
> 2019-01-02 20:55:04.162: warning: 140737013049088: Did not discover a suitable Registration API via DNS-SD
> 2019-01-02 20:55:04.162: info: 140737013049088: Attempting discovery of a Registration API
> 2019-01-02 20:55:04.162: error: 140737281615616: DNSServiceBrowse reported error: -65540

Built on Linux using gcc 6.2 and glibc < 2.18 and running mDNSresponder 878.70.2.

**Comment by garethsb-sony** [comment]
Thanks, I'll investigate.

**Comment by garethsb-sony** [comment]
I don't think this is due to an undefined domain. I think this is related to https://github.com/AMWA-TV/nmos-discovery-registration/pull/71, specifically https://github.com/AMWA-TV/nmos-discovery-registration/pull/71#issuecomment-448212688.

The nmos-cpp code should probably handle this in a different way, but we can't *fix* or even work around the underlying problem except by (a) using avahi rather than mdnsResponder, (b) using the shorter service type proposed in that PR for v1.3, or possibly (c) patching mdnsResponder.

Would you be able to try building and running with avahi to see if that works for you?

**Comment by garethsb-sony** [comment]
If using Avahi isn't an option, the patch in 7432160e07ecb829f324c393ffeec70a75accb33 gets over an initial road-block in the mDNSResponder implementation, but it looks like there are further platform-specific issues with unicast DNS-SD (known as Wide-Area Bonjour or WAB in the mDNSResponder implementation). Some important functions are stubbed out in the Linux platform module.

I've found others have been down the road of trying to fill in the missing functions before: see the thread leading up to [Re: Wide-area Bonjour w/ TSIG auth on (embedded) Linux](https://lists.apple.com/archives/bonjour-dev/2010/Oct/msg00019.html), which links to a patch file for (an ancient version of) mDNSResponder. It's designed to get both unicast browsing _and_ Dynamic DNS Update with [TSIG (Transaction SIGnature)](https://en.wikipedia.org/wiki/TSIG). Since we don't immediately need dynamic DNS, only browsing, to work, simplifying this patch and applying it to a more recent version of mDNSResponder is worth investigating.

**Comment by garethsb-sony** [comment]
Bill and I have determined that we can patch mDNSResponder to make unicast DNS-SD work (limited testing so far of course!). We'll publish this patch shortly, and I'll also update the documentation again to discuss trade-offs between using mDNSResponder and Avahi on Linux.

**Comment by pkeroulas** [comment]
Hello,
I applied the patch for mDNSResponder but couldn't make nmos-cpp-node use DNS-SD.

> 2019-05-21 21:55:05.501: info: 140439073432000: Starting nmos-cpp node
> 2019-05-21 21:55:05.502: info: 140439073432000: Process ID: 8559
> 2019-05-21 21:55:05.502: info: 140439073432000: Initial settings: {"connection_port":1080,"domain":"elslabmedia.cbcrc.ca","don't worry":"about trailing commas","host_address":"192.168.39.88","host_addresses":["192.168.39.88","192.168.2.206","172.17.0.1"],"http_port":1080,"label":"Virtual node 001","logging_level":-40,"logging_port":1080,"node_port":1080,"registration_port":1080,"seed_id":"74acc06d-a13e-4b7c-b124-89e2addc3a55","settings_port":1080}
> 2019-05-21 21:55:05.502: info: 140439073432000: Configuring nmos-cpp node with its primary Node API at: 192.168.39.88:1080
> 2019-05-21 21:55:05.539: info: 140439073432000: Preparing for connections
> 2019-05-21 21:55:05.540: info: 140439073432000: Ready for connections
> 2019-05-21 21:55:05.540: info: 140438912624384: Registered advertisement for: nmos-cpp_node_192-168-39-88:1080._nmos-node._tcp.elslabmedia.cbcrc.ca
> 2019-05-21 21:55:05.544: more info: 140438535018240: Trying Registration API discovery for about 1.000 seconds
> 2019-05-21 21:55:05.544: info: 140438535018240: Attempting discovery of a Registration API
> 2019-05-21 21:55:05.544: info: 140439023920896: Updated model with node: 4255f4f3-657a-587e-b13b-79819f7f4790
> 2019-05-21 21:55:05.544: too much info: 140439023920896: Notifying node behaviour thread
> 2019-05-21 21:55:05.544: more info: 140438887446272: DNSServiceBrowse for regtype: _nmos-registration._tcp domain: elslabmedia.cbcrc.ca on interface: 0
> 2019-05-21 21:55:05.544: more info: 140438895838976: DNSServiceBrowse for regtype: _nmos-register._tcp domain: elslabmedia.cbcrc.ca on interface: 0
> 2019-05-21 21:55:05.554: info: 140439023920896: Updated model with device: b82bd055-4a9d-56cf-94e2-29312fe05bb4
> 2019-05-21 21:55:05.554: too much info: 140439023920896: Notifying node behaviour thread
> 2019-05-21 21:55:05.565: info: 140439023920896: Updated model with source: 5db77a12-e8f0-5048-88e4-8c8a0ad7bdba
> 2019-05-21 21:55:05.565: too much info: 140439023920896: Notifying node behaviour thread
> 2019-05-21 21:55:05.575: info: 140439023920896: Updated model with flow: 58bcefde-895b-51c7-adfc-de5acc6f7cd3
> 2019-05-21 21:55:05.575: too much info: 140439023920896: Notifying node behaviour thread
> 2019-05-21 21:55:05.585: info: 140439023920896: Updated model with sender: caee2369-4fb3-58c5-a3e6-df67248e510e
> 2019-05-21 21:55:05.586: too much info: 140439023920896: Notifying node behaviour thread
> 2019-05-21 21:55:05.596: info: 140439023920896: Updated model with sender: caee2369-4fb3-58c5-a3e6-df67248e510e
> 2019-05-21 21:55:05.596: too much info: 140439023920896: Notifying node behaviour thread
> 2019-05-21 21:55:05.606: info: 140439023920896: Updated model with receiver: 61faeb89-18b7-55cf-b0a9-acae14cadbd8
> 2019-05-21 21:55:05.607: too much info: 140439023920896: Notifying node behaviour thread
> 2019-05-21 21:55:05.617: info: 140439023920896: Updated model with receiver: 61faeb89-18b7-55cf-b0a9-acae14cadbd8
> 2019-05-21 21:55:05.617: too much info: 140439023920896: Notifying node behaviour thread
> 2019-05-21 21:55:06.544: more info: 140438887446272: After DNSServiceBrowse, DNSServiceProcessResult timed out or was cancelled
> 2019-05-21 21:55:06.545: more info: 140438895838976: After DNSServiceBrowse, DNSServiceProcessResult timed out or was cancelled
> 2019-05-21 21:55:06.545: warning: 140438535018240: Did not discover a suitable Registration API via DNS-SD
> 2019-05-21 21:55:06.545: info: 140438535018240: Adopting peer-to-peer operation

We try to keep as close as possible to the AMWA documentation with very similar dnsmasq config. The DNS server is tested with dig and another NMOS client.

But this is a bit strange:
> DNSServiceBrowse for regtype: _nmos-registration._tcp

mDNSResponder shows an error:
> May 21 17:57:11 nmos-desktop mDNSResponder[8556]: Bad service type in ._nmos-registration._tcp.elslabmedia.cbcrc.ca. Application protocol name must be underscore plus 1-15 characters. See <http://www.dns-sd.org/ServiceTypes.html>

Looking closer at the mDNSResponder code base, it turns out:
name->c=""
type->c="_nmos-registration._tcp"  (triggers the error msg)
domain="elslabmedia.cbcrc.ca"

**Comment by garethsb-sony** [comment]
> I applied the patch for mDNSResponder but couldn't make nmos-cpp-node use DNS-SD.

I think I actually forgot to publish the patch to make unicast DNS-SD work on Linux... I'll look back for it!

> But this is a bit strange:
>
> > DNSServiceBrowse for regtype: _nmos-registration._tcp
> 
> mDNSResponder shows an error:

That could suggest mDNSResponder hasn't been patched. However, the important thing is that if you're using IS-04 v1.3, that error doesn't matter because the `_nmos-register._tcp` service type solves the problem by being shorter.
