### ISSUE TITLE
Sandbox not building with USE_ADD_SUBDIRECTORY

### ISSUE THREAD

**Issue by tljdebrouwer** [sony/nmos-cpp#416]
Hello,

When I try to run the sandbox with USE_ADD_SUBDIRECTORY set, I'm getting an error about the conanfile.txt not found, I'm not really good in conan to see where this would need to be fixed, as the conan_provider.cmake is simply using CMAKE_SOURCE_DIR which is the project source direct. 

Any help is appreciated!

```
-- CMake-Conan: Installing single configuration Debug
-- CMake-Conan: conan install /Users/tomdebrouwer/Code/src/libraries/nmos-cpp/Sandbox/my-nmos-node -of=/Users/tomdebrouwer/Code/src/libraries/nmos-cpp/Sandbox/my-nmos-node/conan --profile:host=default;--profile:host=/Users/tomdebrouwer/Code/src/libraries/nmos-cpp/Sandbox/my-nmos-node/conan_host_profile;--profile:build=default;--build=missing
ERROR: Conanfile not found at /Users/tomdebrouwer/Code/src/libraries/nmos-cpp/Sandbox/my-nmos-node/conanfile.txt
CMake Error at /Users/tomdebrouwer/Code/src/libraries/nmos-cpp/Development/third_party/cmake/conan_provider.cmake:436 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  /Users/tomdebrouwer/Code/src/libraries/nmos-cpp/Development/third_party/cmake/conan_provider.cmake:543 (conan_install)
  /Users/tomdebrouwer/Code/src/libraries/nmos-cpp/Development/cmake/NmosCppDependencies.cmake:19 (find_package)
  /Users/tomdebrouwer/Code/src/libraries/nmos-cpp/Development/CMakeLists.txt:29 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by garethsb** [comment]
The issue is that the CMake "top-level include" approach to using the Conan provider requires a top-level _conanfile.(py,txt)_, it doesn't gather conanfiles from the subdirectories (rationale explained in https://github.com/conan-io/cmake-conan/issues/621). So I think the documentation for building the _Sandbox/my-nmos-node_ needs to be clarified.

An **alternative** to using the Conan provider is to install the necessary libraries and then just use the generated toolchain.

Something like I do in [garethsb/nmos-cpp-examples](https://github.com/garethsb/nmos-cpp-examples)... maybe, untested:

```sh
cd Sandbox/my-nmos-node
mkdir build
cd build
conan install ../../Development -g CMakeToolchain --settings:all build_type=<Debug-or-Release> --build=missing --output-folder=conan
cmake .. \
  -DUSE_ADD_SUBDIRECTORY:BOOL=1
  -DCMAKE_BUILD_TYPE:STRING="<Debug-or-Release>" \
  -DCMAKE_TOOLCHAIN_FILE=conan/conan_toolchain.cmake
make
```

**Comment by tljdebrouwer** [comment]
Thanks for the quick reaction.

For now I copied the conanfile to the toplevel directory which gets me through the conan step.
