### ISSUE TITLE
Compilation under Ubuntu Docker

### ISSUE THREAD

**Issue by rhastie** [sony/nmos-cpp#6]
I've followed all the dependencies and successfully compiled the C++ REST SDK under cmake and gcc (quite a few warnings however).

I've now got to compiling the nmos-cpp and successfully ran cmake but under make I get the following error at approx 50%

> /home/nmos-cpp/Development/cpprest/ws_listener_impl.cpp:17:47: fatal error: websocketpp/config/boost_config.hpp: No such file or directory
> compilation terminated.
> CMakeFiles/nmos-cpp-registry.dir/build.make:127: recipe for target 'CMakeFiles/nmos-cpp-registry.dir/cpprest/ws_listener_impl.cpp.o' failed
> make[2]: *** [CMakeFiles/nmos-cpp-registry.dir/cpprest/ws_listener_impl.cpp.o] Error 1
> CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/nmos-cpp-registry.dir/all' failed
> make[1]: *** [CMakeFiles/nmos-cpp-registry.dir/all] Error 2
> Makefile:94: recipe for target 'all' failed
> make: *** [all] Error 2
> root@ubuntu:/home/nmos-cpp/Development/build#

My cmake file is:

> cmake \
>   -G "Unix Makefiles" \
>   -DCMAKE_CONFIGURATION_TYPES:STRING="Debug;Release" \
>   -DBoost_USE_STATIC_LIBS:BOOL="1" \
>   -DBOOST_INCLUDEDIR:PATH="/home/boost_1_67_0" \
>   -DBOOST_LIBRARYDIR:PATH="./home/boost_1_67_0/x64/lib" \
>   -DWEBSOCKETPP_INCLUDE_DIR:PATH="/home/nmos-cpp/Release/libs/websocketpp" \
>   -DCPPREST_INCLUDE_DIR:PATH="/home/cpprestsdk-2.10.2-nmos-cpp/" \
>   -build /home/nmos-cpp/Development/build ..

I believe I'm correctly referencing the boost directories but any assistance on this compilation would be gratefully received

**Comment by rhastie** [comment]
Resolved. I was incorrectly pointing to the incorrect Websocket Include Dir. Correct cmake command below:

> cmake \
>   -G "Unix Makefiles" \
>   -DCMAKE_CONFIGURATION_TYPES:STRING="Debug;Release" \
>   -DBoost_USE_STATIC_LIBS:BOOL="1" \
>   -DBOOST_INCLUDEDIR:PATH="/home/boost_1_67_0" \
>   -DBOOST_LIBRARYDIR:PATH="./home/boost_1_67_0/x64/lib" \
>   -DWEBSOCKETPP_INCLUDE_DIR:PATH="/home/cpprestsdk-2.10.2-nmos-cpp/Release/libs/websocketpp" \
>   -DCPPREST_INCLUDE_DIR:PATH="/home/cpprestsdk-2.10.2-nmos-cpp/" \
>   -build /home/nmos-cpp/Development/build ..

**Comment by garethsb-sony** [comment]
Thanks for the clear report.

I hope the problem is just these two variables:

> -DWEBSOCKETPP_INCLUDE_DIR:PATH="/home/nmos-cpp/Release/libs/websocketpp" 
> -DCPPREST_INCLUDE_DIR:PATH="/home/cpprestsdk-2.10.2-nmos-cpp/" 

The ``CPPREST_INCLUDE_DIR`` needs to point at the location of the C++ REST SDK include root, which I imagine is "/home/cpprestsdk-2.10.2-nmos-cpp/Release/include" for you.

The ``WEBSOCKETPP_INCLUDE_DIR`` needs to be the include root for WebSocket++, which I imagine is "/home/cpprestsdk-2.10.2-nmos-cpp/Release/libs/websocketpp" for you.

Please let me know if that solves your issue.

One other potential issue (unrelated to the problem you are seeing):

> -DCMAKE_CONFIGURATION_TYPES:STRING="Debug;Release" 

The [CMake ``CMAKE_CONFIGURATION_TYPES`` variable](https://cmake.org/cmake/help/latest/variable/CMAKE_CONFIGURATION_TYPES.html) only applies to what CMake calls "multi-configuration generators". For the "Unix Makefiles" generator I think you have to use the ``CMAKE_BUILD_TYPE`` variable instead, to specify a single build type, e.g. "Release".
