### ISSUE TITLE
Feature request: 2022-6 SDP creation/parsing

### ISSUE THREAD

**Issue by wsneijers** [sony/nmos-cpp#74]
Hello,

When looking at the implementation I see SDP generation for 2022-6 (mux flows) is not implemented. It wasn't mentioned in the current feature list, so it was expected. Are there any plans for adding support for 2022-6 SDP files?

Thanks!

**Comment by garethsb-sony** [comment]
Hi Wesley,

The high-level SDP functionality could certainly be expanded - see also #38, #39.

IS-05 [Interpretation of SDP Files](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.1/docs/4.1.%20Behaviour%20-%20RTP%20Transport%20Type.md#interpretation-of-sdp-files) doesn't discuss how to write SDP files for ST 2022-6, and I'm not aware of an implementation with ST 2022-6 myself. ST 2022-6 itself also isn't any help.

It looks like there are snippets/example SDP files in [VSF TR-04:2015](http://www.videoservicesforum.org/download/technical_recommendations/VSF_TR-04_2015-11-12.pdf) that may serve as a starting point, but they're probably incomplete (e.g. no `source-filter` lines).

**Comment by wsneijers** [comment]
Gareth,

Thanks for the quick reply! That can indeed be a good example. I've also seen the following implementation:


v=0
o=- 2082758416640 2082758416640 IN IP4 0.0.0.0
s=eth1-1-video-talker
t=0 0
m=video 10000 RTP/AVP 98
c=IN IP4 239.211.68.1/128
a=source-filter:incl IN IP4 239.211.68.1 0.0.0.0
a=rtpmap:98 SMPTE2022-6/27000000
a=ts-refclk:local

**Comment by garethsb-sony** [comment]
In order to ensure that we implement something that achieves interoperability, would you raise the topic of ST 2022-6 SDP files in the AMWA Basecamp?

**Comment by wsneijers** [comment]
Sure, I will raise the topic. One thing I find strange though; There is no clear definition, but they do provide an example in their own testing tool: https://github.com/AMWA-TV/nmos-testing/blob/master/test_data/IS0401/mux.sdp

**Comment by garethsb-sony** [comment]
That's a good point. It means that the deprecated Node API connection management `/target` endpoint of a Receiver with format `urn:x-nmos:format:mux` would be tested by the IS-04-01 suite (`IS0401Test.test_13`). However, the IS-05 tests use https://github.com/Streampunk/sdpoker which doesn't look like it supports an `a=rtpmap` line with encoding `SMPTE2022-6`, so the test suite could do with some enhancements in this area.

**Comment by wsneijers** [comment]
Hi Gareth,

I did receive a response from the AMWA Basecamp. It is actually defined in the ST2022-8 standard. At the moment I only have a draft of the standard, so I don't have a complete picture yet. Looking at the standard it says that it should comply with the definition in the St2110-10 standard, with the exception that the rtpmap has the following format:

`a=rtpmap:<PT> SMPTE2022-6/27000000`

However this still raises questions. For example should it also include the `a=fmtp` key? And if so what parameters should be included? Again I only have the draft, so no clear conclusions yet.

**Comment by garethsb-sony** [comment]
Yes, good to have Thomas point us in the right direction! I think I can get hold of the final ST 2022-8, so I'll update this issue with relevant info.

**Comment by garethsb-sony** [comment]
So, ST 2022-8:2019 is terse, with no examples of the SDP.

Section 7.1, Session Description of SMPTE ST 2022-6 Streams, says:
"SMPTE ST 2022-6 senders compliant to this standard shall comply with the Session Description Protocol as specified in SMPTE ST 2110-10, with the exception that the requirement of separate SDP objects for each RTP stream is relaxed for the case of SMPTE ST 2022-5 FEC which shall be as described below.
Mapping of the 2022-6 media type into SDP shall use the media type definition defined in section 8.1. "

Section 8.1 just defines `video/SMPTE2022-6` that @wsneijers mentions above.

I agree that doesn't make it clear whether/what `fmtp` attribute should be included, since ST 2110-10 only explicitly mentions requiring the `mediaclk` and `ts-refclk` attributes, and then says "Additional requirements of the SDP object may be specified in the media essence-specific requirements documents".

I'll respond on Basecamp.

**Comment by garethsb-sony** [comment]
OK, based on Thomas's most recent response, `fmtp` is not specified for `video/SMPTE2022-6`.

Therefore I see only a few problems with your sample SDP file above (https://github.com/sony/nmos-cpp/issues/74#issuecomment-494320735):

* If I'm being picky, it's missing a space before `incl` in the `source-filter` attribute
* I think ST 2110-10 requires `ts-refclk` attribute to use either the `ptp` form or the (ST 2110-10 invented) `localmac` form, not `local`
* I think ST 2110-10 requires a `mediaclk` attribute with the `direct` form

Extending nmos/sdp_utils.h to generate and parse such SDP files should be relatively straightforward.

**Comment by wsneijers** [comment]
Gareth,

I agree. However I keep finding it strange that key information about a stream is not included in ST2022-6 SDP. Though as far as I understand you can still add it if you want. Also the S2022-8 is a bit vague to say the least. And indeed now you mention it the example SDP does have some quirks.

Is adding ST2022-6 SDP support to nmos-ccp something on your roadmap? Or can I add it myself?

**Comment by garethsb-sony** [comment]
I think there are two things to do then.

(a) If you would like to make a PR for update to nmos/sdp_utils.{cpp,h} to add matching functions that parse/generate SDP files for `urn:x-nmos:transport:mux` according to current ST 2022-8, I'll happily review and look to merge; otherwise I would get to this at some point, but not immediately

(b) If you would like to list up the additional info/params that you think ought to be included in SDP for ST 2022-6, we seem to have Thomas's attention, so contributing that feedback in Basecamp would be great.
