### ISSUE TITLE
Application hooks: notification about IS-05 connection changes

### ISSUE THREAD

**Issue by jwpwh** [sony/nmos-cpp#85]
One of the hooks I had proposed was called "resource_activation" and was essentially called from the connection_activation_thread after updating an IS-05 resource and any corresponding IS-04 resource. The purpose of the call was to notify the application that a change had been made so that it could "react" to the changes and do the application specific actions needed to actually make a connection happen. 

In the example, nothing was done so maybe it looked like this function was not needed but somehow, this notification needs to be made. Without the notification, a connection resource change is made to the model but nothing actually changes in the application.  Is there some other mechanism by which the application can be notified when connection resources are changed?

Thanks.

**Comment by garethsb-sony** [comment]
I was thinking that asynchronous notification via the model condition variable, using the update timestamps on the (IS-04 `resources` or IS-05 `connection_resources`) sender or receiver to identify changes, would be sufficient. But I can see that a synchronous notification could be important.

If you would like a synchronous notification, we could add something like this to the `connection_activation_thread`:

```C++
namespace nmos
{
    // a connection_activation_handler is a notification that the active parameters for the specified (IS-04/IS-05)
    // sender/connection_sender or receiver/connection_receiver have changed
    typedef std::function<void(const nmos::resource&, const nmos::resource&)> connection_activation_handler;
}
```

(Since the model lock will continue to be held during this call, it cannot be updated, hence no `bool` return to indicate `model.notify()` should be called.)

The tricky bit may be whether to allow this callback to throw exceptions to indicate that the activation didn't succeed, as the two existing callbacks do. The spec says that "if there is an error condition that means `auto` cannot be resolved, the active transport parameters must not change, and the underlying receiver must continue as before." This would seem to be a good model to follow generally during activation.

If the callback were not allowed to throw exceptions, it can simply be called after updating both the IS-05 and IS-04 resources. If activation were to fail at this point, the application would need to asynchronously update the resources appropriately in another thread.

If the callback were allowed to throw exceptions, do we need to call it early enough to avoid actually modifying the (IS-05) transport params, transport file and (IS-04) subscription info, or be able to restore them?

**Comment by jwpwh** [comment]
In general, it seems like allowing exceptions would give the most flexibility.  If done, it seems like the callback needs to know what the desired changed resources would look like so either making the changes and restoring on exceptions or having proposed changes and applying if no exception would probably work. I am assuming that exceptions would provide a mechanism of sending back a reply indicating the reason for the exception.

The callback as originally put in was done after the changes were made and no opportunity for a meaningful reply existed. Some of the meaningful replies that would be nice to give could probably be handled by exceptions from the other callbacks. I am not sure that all can be.

As currently being used, the activation callback can fail if there is an attempt to connect something like a video to an audio. Some audio senders may also be incompatible with some receivers. We don't currently handle turning senders off or making changes to some sender parameters through IS-05 and attempts to make changes are just ignored. Meaningful replies instead of silently ignoring would be preferred.

The original activation callback is used to make or break a connection as well as do some validation of the proposed connection.

**Comment by garethsb-sony** [comment]
Thank you, that's all useful insight.

> As currently being used, the activation callback can fail if there is an attempt to connect something like a video to an audio. Some audio senders may also be incompatible with some receivers. We don't currently handle turning senders off or making changes to some sender parameters through IS-05 and attempts to make changes are just ignored. Meaningful replies instead of silently ignoring would be preferred.

There is a very limited wherewithal in the spec to send error information back to the ultimate client that sent the `PATCH /staged` request. However...

> Some of the meaningful replies that would be nice to give could probably be handled by exceptions from the other callbacks. I am not sure that all can be.

Basically speaking, in the current implementation, the `parse_transport_file` and `validate_merged` hooks allows the sender/receiver to reject PATCH /staged requests with either 400 Bad Request or 500 Internal Error and a `"debug"` message in the response body from the exception.

This should cover the connection of a video sender to an audio receiver and other media-related parameter mismatches, so long as an SDP file is used in the PATCH request.

The `validate_merged` hook should also allow you to reject turning senders off or making changes to some sender parameters through IS-05. For example just throw `std::logic_error` with a meaningful error message if the merged data has `"master_enable": false`.

That leaves errors that happen when /staged parameters are transitioned to /active. There are currently two hooks at this point, `resolve_auto` and, for senders, `set_transportfile`.

In the case of scheduled activations, there is simply no way to indicate any error directly to the client that made the PATCH request - they will have already received a 202 Accepted. There's no way in the spec for a client to receive a push notification of failure, it can only check the /active and /staged endpoints, or perhaps spot the *absence* of a notification (via resource registration to the Registry and then) via Query WebSocket, after the scheduled activation time.

On the other hand, for immediate activations, the spec allows to return a 400 or 500 status code, which is implemented by throwing an exception from `resolve_auto` or `set_transportfile`. (At the moment, the exception message is not passed back so it cannot be embedded into the immediate activation response. I'm not sure how important this is...)

These two hooks hopefully cover more of the application-specific possible reasons for failure. But they are, like the other hooks above, called synchronously with the model locked, so are expected not to wait for async operations.

Even if we add a further `connection_activated` hook after these, I think any check that requires analysis of the sender/receiver to which this receiver/sender is being connected is not reasonable to do synchronously at this point, or one slow sender/receiver could block activation of other senders/receivers?

Therefore, I'm not sure how useful supporting exceptions from this hook would be. Perhaps at this point, it's reasonable that the `/active` endpoint and IS-04 resource are updated to show a successful make or break. If some asynchronous operation fails, the application-specific code should update the `/active` endpoint and IS-04 resource itself (using the helper functions provided).

What do you think?

**Comment by jwpwh** [comment]
You make some very good points. Thank you.

I think I will try to make use of the other mechanisms you have mentioned for the validations. I suspect I may still want a connection_activated hook for the actual connection work but probably without exceptions will be fine. I will let you know how it goes.

Thanks again.

**Comment by garethsb-sony** [comment]
OK, I'll add the `connection_activated` hook on that basis today, and we can both evaluate it - I'll probably kill two birds with one stone and add an IS-07 WebSocket Receiver to the example nmos-cpp-node to try it out!

**Comment by garethsb-sony** [comment]
> OK, I'll add the `connection_activated` hook on that basis today

Done, see 5aaa0168f74b7cf00addd3affad927f291b275f1.

**Comment by garethsb-sony** [comment]
Just as an update, I am currently wrestling with whether synchronous callbacks while holding a lock on the `nmos::model` mutex are a good idea. If an application needs to lock some other implementation-specific resource in the callback, there is a chance of deadlock unless the application always locks the `nmos::model` mutex first everywhere it acquires both.

**Comment by jwpwh** [comment]
I do have my own mutex so in general your concern is valid.

I checked my existing code and most of my functions where I lock my own mutex are called from code which first locks the model mutex before calling the functions that lock my own mutex. I currently have 1 spot that doesn't do this and it would be easy to change and it is only called once. So I can live with having to lock the model mutex first.

Do you have another alternative in mind?

**Comment by garethsb-sony** [comment]
Two possible alternatives, though neither fully thought out:

* Asynchronous notification, probably with the kind of 'logical' locking using activation timestamps already used between the Connection API and the activation thread for immediate activations.
* Synchronous notification with the model mutex unlocked - using `reverse_lock` around the callback - requiring the activation thread to re-examine the state of the model after the callback returns.

**Comment by jwpwh** [comment]
When I get the notification about the connection, I am sending a message to start making or breaking the connection. Most of the actual work will be done asynchronously to the notification.   In that sense, whether it probably doesn't matter whether it is asynch or synch. 

I assume the "node_implementation_thread" could be used to find the recently completed activations (as opposed to the requested activations that the activation thread is looking for)

I think I can easily go either way.


I think I have the latest code integrated into my application. I am going to suggest a couple of changes  based on my experience. I have a little bit of clean up to do to complete the transition from the old to the new and then I will isolate the code for my suggestions in a pull request.

**Comment by garethsb-sony** [comment]
I'll leave things as they are for now, with `connection_activated` being a synchronous callback, which shouldn't throw exceptions and which is called with the model locked.

I've been playing around, tweaking `nmos::connection_activation_thread` and the new `nmos::make_connection_events_websocket_activation_handler` used in the example nmos-cpp-node, to see if I could get immediate activations to report 500 Internal Error when e.g. opeing the WebSocket connection failed, by `wait`-ing for the `subscribe` task in the case of an immediate activation rather than just letting it go asynchronously with an `observe_exception`. By connecting the node's WebSocket Receiver to its own Sender, I was able to deadlock that as expected. Getting this to work would require a rewrite of the `nmos::connection_activation_thread` loop to allow the model to be unlocked for the callback (and thus passing an `id` rather than the `resource`), or fragile logic in `nmos::make_connection_events_websocket_activation_handler` to avoid `wait`-ing for self-connections. I'm not going to pursue either of those for now.
